import HomePage from './components/home/HomePage';
import Form from './components/form/Form';
import Quemsomos from './components/quemsomos/Quemsomos';
import Skiils from './components/skills/Skiils';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ideal Planos de Saude </title>
          <meta content="width=device-width, initial-scale=1" name="viewport" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />


          <script 
            async
            src={'https://www.googletagmanager.com/gtag/js?id=GTM-5HDGPBQ'}
          />
          
          <Script strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-5HDGPBQ');`}}></Script>

      </Head>
      <main className={styles.main}>



      <HomePage />
      <Quemsomos />
      <Skiils />
      <Form />





      </main>
    </>
  )
}
